# Generated by Django 5.0.6 on 2024-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Username')),
                ('telegram_id', models.PositiveBigIntegerField(verbose_name='Telegram ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined at')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
            },
        ),
    ]
